### ISSUE TITLE
connect to the navbar

### ISSUE THREAD

**Issue by bagratzakaryan** [codrops/PageRevealEffects#2]
Hello, thank you for a plugin, it is a good job.
If you don’t mind I have a question, could you help me, please?
I have tried to connect my navbar and logo(homepage) clicks to this plugin, but have a problem with the code, it will be great to solve this problem, Thank you very much.
Here is the code by which I connected navbar and logo(homepage) to the plugin.

(function() {

	var pages = [].slice.call(document.querySelectorAll('.pages > .page')),
		currentPage = 0,
		
		revealerOpts = {
			// the layers are the elements that move from the sides
			nmbLayers : 3,
			// bg color of each layer
			bgcolor : ['#52b7b9', '#ffffff', '#53b7eb'],
			// effect classname
			effect : 'anim--effect-3'
		};
		revealer = new Revealer(revealerOpts);

	// clicking the page nav
	var navbar = document.getElementById("navbar").getElementsByTagName("a");
	var n;
	for (var i = 0; i < navbar.length; i++) {
		navbar[i].addEventListener('click', function() {n = i; reveal('top'); });
	}
	
	// triggers the effect by calling instance.reveal(direction, callbackTime, callbackFn)
	function reveal(direction) {
			var callbackTime = 750;

	        callbackFn = function() {

	        	// this is the part where is running the turning of pages
            	classie.remove(pages[currentPage], 'page--current');

            	currentPage = n;

            	classie.add(pages[currentPage], 'page--current');

	        };

	    revealer.reveal(direction, callbackTime, callbackFn);
	} 

})();

**Comment by botelho** [comment]
Hi, I noticed you asked the same question in the Codrops article's comments, so let's close this with the hope somebody answers you on the blog. Let´s keep this here only for bugs & issues. Cheers.
